version: '3'

services:
  manolibakes:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - debug.env
    entrypoint:
      [
        "python3",
        "/app/manage.py",
        "runserver",
        "0.0.0.0:8001"
      ]
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - debug.env
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/usr/shared/postgres/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_admin" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-volume:
    driver: local
