# docker-compose.yml
services:
  # web:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   command: python manolibakes/manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - .:/code

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 5432:5432



volumes:
  postgres_data:
