version: '3'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/var/sqlite
    env_file:
      - docker.env
    entrypoint: [ "python3", "/app/manage.py", "runserver", "0.0.0.0:8001" ]
    ports:
      - 8001:8001
