[tool.poetry]
name = "pan-manoli"
version = "0.1.0"
description = ""
authors = ["Javier Linares <jlinarestorres2@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10.1,<3.13"
django = "^4.2.5"
pydantic = "^2.4.2"
pandas = "^2.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
