# Generated by Django 4.2.5 on 2023-10-13 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('L', 'lunes'), ('M', 'martes'), ('X', 'miércoles'), ('J', 'jueves'), ('V', 'viernes'), ('S', 'sábado'), ('D', 'domingo')], max_length=2)),
                ('number', models.PositiveIntegerField(default=0)),
                ('bread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bread')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number', models.PositiveIntegerField(default=0)),
                ('bread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bread')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='weeklydefaults',
            constraint=models.UniqueConstraint(fields=('customer', 'bread', 'weekday'), name='unique-weekly-default'),
        ),
    ]
