# Generated by Django 4.2.5 on 2023-10-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_weeklydefaults_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklydefaults',
            name='weekday',
            field=models.PositiveIntegerField(choices=[('0', 'lunes'), ('1', 'martes'), ('2', 'miércoles'), ('3', 'jueves'), ('4', 'viernes'), ('5', 'sábado'), ('6', 'domingo')]),
        ),
    ]
