# Generated by Django 4.2.5 on 2023-10-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_weeklydefaults_weekday'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('customer', 'bread', 'date'), name='unique-order'),
        ),
    ]
