# Generated by Django 4.2.5 on 2023-10-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_unique_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
