# Generated by Django 4.2.5 on 2024-01-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lastname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
