# Generated by Django 4.2.5 on 2024-01-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_customer_lastname'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('name', 'lastname'), name='unique-name-lastname'),
        ),
    ]
