# Generated by Django 4.2.5 on 2024-01-06 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customer_unique_name_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0)),
                ('bread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bread')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dailydefaults',
            constraint=models.UniqueConstraint(fields=('customer', 'bread'), name='unique-daily-default'),
        ),
    ]
