# Generated by Django 6.0.4 on 2026-05-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_customer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bread',
            options={'verbose_name': 'bread', 'verbose_name_plural': 'breads'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
