# Generated by Django 6.0.4 on 2026-05-04 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_bread_options_alter_customer_lastname'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weeklydefaults',
            name='unique-weekly-default',
        ),
        migrations.DeleteModel(
            name='WeeklyDefaults',
        ),
    ]
