# Generated by Django 6.0.4 on 2026-05-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_weeklydefaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='bread',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='breads/'),
        ),
    ]
