# Generated by Django 6.0.4 on 2026-05-10 15:43

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_bread_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bread',
            name='name',
            field=core.fields.TitleCaseCharField(max_length=200),
        ),
    ]
